apiVersion: v2
name: danswer-stack
description: A Helm chart for Kubernetes
home: https://www.danswer.ai/
sources:
  - "https://github.com/danswer-ai/danswer"
type: application
version: 0.2.1
appVersion: "latest"
annotations:
  category: Productivity
  licenses: MIT
  images: |
    - name: webserver
      image: docker.io/danswer/danswer-web-server:latest
    - name: background
      image: docker.io/danswer/danswer-backend:latest
    - name: vespa
      image: vespaengine/vespa:8.277.17
dependencies:
  - name: postgresql
    version: 14.3.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: vespa
    version: 0.2.16
    repository: https://danswer-ai.github.io/vespa-helm-charts
    condition: vespa.enabled
  - name: nginx
    version: 15.14.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: nginx.enabled
  - name: redis
    version: 20.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
