apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: celery-worker-primary-scaledobject
  namespace: danswer
  labels:
    app: celery-worker-primary
spec:
  scaleTargetRef:
    name: celery-worker-primary
  pollingInterval: 15 # Check every 15 seconds
  cooldownPeriod: 30 # Wait 30 seconds before scaling down
  minReplicaCount: 1
  maxReplicaCount: 1
  triggers:
    - type: redis
      metadata:
        host: "{host}"
        port: "6379"
        enableTLS: "true"
        listName: celery
        listLength: "1"
        databaseIndex: "15"
      authenticationRef:
        name: celery-worker-auth

    - type: redis
      metadata:
        host: "{host}"
        port: "6379"
        enableTLS: "true"
        listName: celery:1
        listLength: "1"
        databaseIndex: "15"
      authenticationRef:
        name: celery-worker-auth
    - type: redis
      metadata:
        host: "{host}"
        port: "6379"
        enableTLS: "true"
        listName: celery:2
        listLength: "1"
        databaseIndex: "15"
      authenticationRef:
        name: celery-worker-auth
    - type: redis
      metadata:
        host: "{host}"
        port: "6379"
        enableTLS: "true"
        listName: celery:3
        listLength: "1"
        databaseIndex: "15"
      authenticationRef:
        name: celery-worker-auth
    - type: redis
      metadata:
        host: "{host}"
        port: "6379"
        enableTLS: "true"
        listName: periodic_tasks
        listLength: "1"
        databaseIndex: "15"
      authenticationRef:
        name: celery-worker-auth
    - type: redis
      metadata:
        host: "{host}"
        port: "6379"
        enableTLS: "true"
        listName: periodic_tasks:2
        listLength: "1"
        databaseIndex: "15"
      authenticationRef:
        name: celery-worker-auth
