apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.inferenceCapability.pvc.name }}
spec:
  storageClassName: {{ .Values.persistent.storageClassName }}
  accessModes: 
    {{- toYaml .Values.inferenceCapability.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.inferenceCapability.pvc.storage }}
